# apps/backend/envs/dev/backend-secret-resource.yaml
apiVersion: v1  
kind: Secret  
metadata:  
  name: backend-secret  
  namespace: devbcn-demo
  annotations:  
    argocd.argoproj.io/sync-wave: "0"    
type: Opaque  
stringData:  
  REDIS_CONN_STR: "redis://redis:6379"  